/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as disciplineRulesSol from "./DisciplineRules.sol";
export type { disciplineRulesSol };
import type * as rewardvaultSol from "./rewardvault.sol";
export type { rewardvaultSol };
export type { SoulboundToken } from "./SoulboundToken";
