/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace DisciplineRules {
  export type UserMonthlyDataStruct = {
    budget: BigNumberish;
    actualSpent: BigNumberish;
    impulseSpent: BigNumberish;
    emergencyFundMonths: BigNumberish;
    timestamp: BigNumberish;
    evaluated: boolean;
  };

  export type UserMonthlyDataStructOutput = [
    budget: bigint,
    actualSpent: bigint,
    impulseSpent: bigint,
    emergencyFundMonths: bigint,
    timestamp: bigint,
    evaluated: boolean
  ] & {
    budget: bigint;
    actualSpent: bigint;
    impulseSpent: bigint;
    emergencyFundMonths: bigint;
    timestamp: bigint;
    evaluated: boolean;
  };
}

export interface DisciplineRulesInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateRewards"
      | "getCurrentMonthData"
      | "hasUsedEmergency"
      | "owner"
      | "recordSpending"
      | "renounceOwnership"
      | "setBudget"
      | "soulboundToken"
      | "tierRequirements"
      | "transferOwnership"
      | "updateEmergencyFund"
      | "updateTierRequirements"
      | "useEmergency"
      | "userBaselineImpulse"
      | "userCurrentMonth"
      | "userMonthlyData"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BudgetSet"
      | "EmergencyUsed"
      | "OwnershipTransferred"
      | "RewardCalculated"
      | "SpendingRecorded"
      | "TierPromoted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentMonthData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUsedEmergency",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordSpending",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBudget",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "soulboundToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tierRequirements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateEmergencyFund",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTierRequirements",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "useEmergency",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userBaselineImpulse",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userCurrentMonth",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userMonthlyData",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentMonthData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUsedEmergency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordSpending",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBudget", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "soulboundToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tierRequirements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEmergencyFund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTierRequirements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "useEmergency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userBaselineImpulse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userCurrentMonth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userMonthlyData",
    data: BytesLike
  ): Result;
}

export namespace BudgetSetEvent {
  export type InputTuple = [
    user: AddressLike,
    month: BigNumberish,
    budget: BigNumberish
  ];
  export type OutputTuple = [user: string, month: bigint, budget: bigint];
  export interface OutputObject {
    user: string;
    month: bigint;
    budget: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyUsedEvent {
  export type InputTuple = [user: AddressLike, month: BigNumberish];
  export type OutputTuple = [user: string, month: bigint];
  export interface OutputObject {
    user: string;
    month: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardCalculatedEvent {
  export type InputTuple = [
    user: AddressLike,
    month: BigNumberish,
    reward: BigNumberish,
    tier: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    month: bigint,
    reward: bigint,
    tier: bigint
  ];
  export interface OutputObject {
    user: string;
    month: bigint;
    reward: bigint;
    tier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpendingRecordedEvent {
  export type InputTuple = [
    user: AddressLike,
    month: BigNumberish,
    actualSpent: BigNumberish,
    impulseSpent: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    month: bigint,
    actualSpent: bigint,
    impulseSpent: bigint
  ];
  export interface OutputObject {
    user: string;
    month: bigint;
    actualSpent: bigint;
    impulseSpent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TierPromotedEvent {
  export type InputTuple = [user: AddressLike, newTier: BigNumberish];
  export type OutputTuple = [user: string, newTier: bigint];
  export interface OutputObject {
    user: string;
    newTier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DisciplineRules extends BaseContract {
  connect(runner?: ContractRunner | null): DisciplineRules;
  waitForDeployment(): Promise<this>;

  interface: DisciplineRulesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateRewards: TypedContractMethod<[], [void], "nonpayable">;

  getCurrentMonthData: TypedContractMethod<
    [user: AddressLike],
    [DisciplineRules.UserMonthlyDataStructOutput],
    "view"
  >;

  hasUsedEmergency: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordSpending: TypedContractMethod<
    [actualSpent: BigNumberish, impulseSpent: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setBudget: TypedContractMethod<[budget: BigNumberish], [void], "nonpayable">;

  soulboundToken: TypedContractMethod<[], [string], "view">;

  tierRequirements: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        budgetCompliancePercent: bigint;
        impulseReductionPercent: bigint;
        emergencyFundMonths: bigint;
        rewardAmount: bigint;
        streakRequired: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateEmergencyFund: TypedContractMethod<
    [months: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateTierRequirements: TypedContractMethod<
    [
      tier: BigNumberish,
      budgetCompliance: BigNumberish,
      impulseReduction: BigNumberish,
      emergencyFund: BigNumberish,
      reward: BigNumberish,
      streak: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  useEmergency: TypedContractMethod<[], [void], "nonpayable">;

  userBaselineImpulse: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  userCurrentMonth: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userMonthlyData: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        budget: bigint;
        actualSpent: bigint;
        impulseSpent: bigint;
        emergencyFundMonths: bigint;
        timestamp: bigint;
        evaluated: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCurrentMonthData"
  ): TypedContractMethod<
    [user: AddressLike],
    [DisciplineRules.UserMonthlyDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasUsedEmergency"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordSpending"
  ): TypedContractMethod<
    [actualSpent: BigNumberish, impulseSpent: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBudget"
  ): TypedContractMethod<[budget: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "soulboundToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tierRequirements"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        budgetCompliancePercent: bigint;
        impulseReductionPercent: bigint;
        emergencyFundMonths: bigint;
        rewardAmount: bigint;
        streakRequired: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateEmergencyFund"
  ): TypedContractMethod<[months: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTierRequirements"
  ): TypedContractMethod<
    [
      tier: BigNumberish,
      budgetCompliance: BigNumberish,
      impulseReduction: BigNumberish,
      emergencyFund: BigNumberish,
      reward: BigNumberish,
      streak: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "useEmergency"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userBaselineImpulse"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userCurrentMonth"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userMonthlyData"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean] & {
        budget: bigint;
        actualSpent: bigint;
        impulseSpent: bigint;
        emergencyFundMonths: bigint;
        timestamp: bigint;
        evaluated: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "BudgetSet"
  ): TypedContractEvent<
    BudgetSetEvent.InputTuple,
    BudgetSetEvent.OutputTuple,
    BudgetSetEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyUsed"
  ): TypedContractEvent<
    EmergencyUsedEvent.InputTuple,
    EmergencyUsedEvent.OutputTuple,
    EmergencyUsedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardCalculated"
  ): TypedContractEvent<
    RewardCalculatedEvent.InputTuple,
    RewardCalculatedEvent.OutputTuple,
    RewardCalculatedEvent.OutputObject
  >;
  getEvent(
    key: "SpendingRecorded"
  ): TypedContractEvent<
    SpendingRecordedEvent.InputTuple,
    SpendingRecordedEvent.OutputTuple,
    SpendingRecordedEvent.OutputObject
  >;
  getEvent(
    key: "TierPromoted"
  ): TypedContractEvent<
    TierPromotedEvent.InputTuple,
    TierPromotedEvent.OutputTuple,
    TierPromotedEvent.OutputObject
  >;

  filters: {
    "BudgetSet(address,uint256,uint256)": TypedContractEvent<
      BudgetSetEvent.InputTuple,
      BudgetSetEvent.OutputTuple,
      BudgetSetEvent.OutputObject
    >;
    BudgetSet: TypedContractEvent<
      BudgetSetEvent.InputTuple,
      BudgetSetEvent.OutputTuple,
      BudgetSetEvent.OutputObject
    >;

    "EmergencyUsed(address,uint256)": TypedContractEvent<
      EmergencyUsedEvent.InputTuple,
      EmergencyUsedEvent.OutputTuple,
      EmergencyUsedEvent.OutputObject
    >;
    EmergencyUsed: TypedContractEvent<
      EmergencyUsedEvent.InputTuple,
      EmergencyUsedEvent.OutputTuple,
      EmergencyUsedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardCalculated(address,uint256,uint256,uint256)": TypedContractEvent<
      RewardCalculatedEvent.InputTuple,
      RewardCalculatedEvent.OutputTuple,
      RewardCalculatedEvent.OutputObject
    >;
    RewardCalculated: TypedContractEvent<
      RewardCalculatedEvent.InputTuple,
      RewardCalculatedEvent.OutputTuple,
      RewardCalculatedEvent.OutputObject
    >;

    "SpendingRecorded(address,uint256,uint256,uint256)": TypedContractEvent<
      SpendingRecordedEvent.InputTuple,
      SpendingRecordedEvent.OutputTuple,
      SpendingRecordedEvent.OutputObject
    >;
    SpendingRecorded: TypedContractEvent<
      SpendingRecordedEvent.InputTuple,
      SpendingRecordedEvent.OutputTuple,
      SpendingRecordedEvent.OutputObject
    >;

    "TierPromoted(address,uint256)": TypedContractEvent<
      TierPromotedEvent.InputTuple,
      TierPromotedEvent.OutputTuple,
      TierPromotedEvent.OutputObject
    >;
    TierPromoted: TypedContractEvent<
      TierPromotedEvent.InputTuple,
      TierPromotedEvent.OutputTuple,
      TierPromotedEvent.OutputObject
    >;
  };
}
