/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DisciplineRules } from "./DisciplineRules";
export type { ISoulboundToken } from "./ISoulboundToken";
