/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ISoulboundToken {
  export type TokenDataStruct = {
    porBalance: BigNumberish;
    totalEarned: BigNumberish;
    currentTier: BigNumberish;
    consecutiveMonths: BigNumberish;
    lastRewardTime: BigNumberish;
    isActive: boolean;
  };

  export type TokenDataStructOutput = [
    porBalance: bigint,
    totalEarned: bigint,
    currentTier: bigint,
    consecutiveMonths: bigint,
    lastRewardTime: bigint,
    isActive: boolean
  ] & {
    porBalance: bigint;
    totalEarned: bigint;
    currentTier: bigint;
    consecutiveMonths: bigint;
    lastRewardTime: bigint;
    isActive: boolean;
  };
}

export interface ISoulboundTokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addressToTokenId"
      | "hasMinted"
      | "spendReward"
      | "tokenData"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addressToTokenId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasMinted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "spendReward",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenData",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addressToTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasMinted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "spendReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenData", data: BytesLike): Result;
}

export interface ISoulboundToken extends BaseContract {
  connect(runner?: ContractRunner | null): ISoulboundToken;
  waitForDeployment(): Promise<this>;

  interface: ISoulboundTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addressToTokenId: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  hasMinted: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  spendReward: TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokenData: TypedContractMethod<
    [tokenId: BigNumberish],
    [ISoulboundToken.TokenDataStructOutput],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addressToTokenId"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasMinted"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "spendReward"
  ): TypedContractMethod<
    [tokenId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tokenData"
  ): TypedContractMethod<
    [tokenId: BigNumberish],
    [ISoulboundToken.TokenDataStructOutput],
    "view"
  >;

  filters: {};
}
