/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace RewardVault {
  export type VaultStruct = {
    vaultType: BigNumberish;
    targetAmount: BigNumberish;
    currentAmount: BigNumberish;
    tokensSpent: BigNumberish;
    createdAt: BigNumberish;
    targetDate: BigNumberish;
    isActive: boolean;
    description: string;
  };

  export type VaultStructOutput = [
    vaultType: bigint,
    targetAmount: bigint,
    currentAmount: bigint,
    tokensSpent: bigint,
    createdAt: bigint,
    targetDate: bigint,
    isActive: boolean,
    description: string
  ] & {
    vaultType: bigint;
    targetAmount: bigint;
    currentAmount: bigint;
    tokensSpent: bigint;
    createdAt: bigint;
    targetDate: bigint;
    isActive: boolean;
    description: string;
  };
}

export interface RewardVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveProvider"
      | "createVault"
      | "depositToVault"
      | "getUserVaults"
      | "owner"
      | "porToUsdRate"
      | "providerList"
      | "renounceOwnership"
      | "serviceProviders"
      | "soulboundToken"
      | "transferOwnership"
      | "userVaultCount"
      | "userVaults"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ProviderApproved"
      | "TokensDeposited"
      | "VaultCreated"
      | "VaultUsed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveProvider",
    values: [AddressLike, string, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createVault",
    values: [BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToVault",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserVaults",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "porToUsdRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "providerList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "serviceProviders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "soulboundToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userVaultCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userVaults",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveProvider",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserVaults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "porToUsdRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "providerList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serviceProviders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "soulboundToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userVaultCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userVaults", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProviderApprovedEvent {
  export type InputTuple = [
    provider: AddressLike,
    name: string,
    vaultType: BigNumberish
  ];
  export type OutputTuple = [provider: string, name: string, vaultType: bigint];
  export interface OutputObject {
    provider: string;
    name: string;
    vaultType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensDepositedEvent {
  export type InputTuple = [
    user: AddressLike,
    vaultId: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, vaultId: bigint, amount: bigint];
  export interface OutputObject {
    user: string;
    vaultId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultCreatedEvent {
  export type InputTuple = [
    user: AddressLike,
    vaultId: BigNumberish,
    vaultType: BigNumberish,
    targetAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    vaultId: bigint,
    vaultType: bigint,
    targetAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    vaultId: bigint;
    vaultType: bigint;
    targetAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultUsedEvent {
  export type InputTuple = [
    user: AddressLike,
    vaultId: BigNumberish,
    provider: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    vaultId: bigint,
    provider: string,
    amount: bigint
  ];
  export interface OutputObject {
    user: string;
    vaultId: bigint;
    provider: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RewardVault extends BaseContract {
  connect(runner?: ContractRunner | null): RewardVault;
  waitForDeployment(): Promise<this>;

  interface: RewardVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveProvider: TypedContractMethod<
    [
      provider: AddressLike,
      name: string,
      paymentAddress: AddressLike,
      allowedVaultType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  createVault: TypedContractMethod<
    [
      vaultType: BigNumberish,
      targetAmount: BigNumberish,
      targetDate: BigNumberish,
      description: string
    ],
    [bigint],
    "nonpayable"
  >;

  depositToVault: TypedContractMethod<
    [vaultId: BigNumberish, porAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getUserVaults: TypedContractMethod<
    [user: AddressLike],
    [RewardVault.VaultStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  porToUsdRate: TypedContractMethod<[], [bigint], "view">;

  providerList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  serviceProviders: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean] & {
        name: string;
        paymentAddress: string;
        allowedVaultType: bigint;
        isApproved: boolean;
      }
    ],
    "view"
  >;

  soulboundToken: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userVaultCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userVaults: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean, string] & {
        vaultType: bigint;
        targetAmount: bigint;
        currentAmount: bigint;
        tokensSpent: bigint;
        createdAt: bigint;
        targetDate: bigint;
        isActive: boolean;
        description: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveProvider"
  ): TypedContractMethod<
    [
      provider: AddressLike,
      name: string,
      paymentAddress: AddressLike,
      allowedVaultType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createVault"
  ): TypedContractMethod<
    [
      vaultType: BigNumberish,
      targetAmount: BigNumberish,
      targetDate: BigNumberish,
      description: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositToVault"
  ): TypedContractMethod<
    [vaultId: BigNumberish, porAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getUserVaults"
  ): TypedContractMethod<
    [user: AddressLike],
    [RewardVault.VaultStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "porToUsdRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "providerList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "serviceProviders"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, bigint, boolean] & {
        name: string;
        paymentAddress: string;
        allowedVaultType: bigint;
        isApproved: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "soulboundToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userVaultCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userVaults"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean, string] & {
        vaultType: bigint;
        targetAmount: bigint;
        currentAmount: bigint;
        tokensSpent: bigint;
        createdAt: bigint;
        targetDate: bigint;
        isActive: boolean;
        description: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProviderApproved"
  ): TypedContractEvent<
    ProviderApprovedEvent.InputTuple,
    ProviderApprovedEvent.OutputTuple,
    ProviderApprovedEvent.OutputObject
  >;
  getEvent(
    key: "TokensDeposited"
  ): TypedContractEvent<
    TokensDepositedEvent.InputTuple,
    TokensDepositedEvent.OutputTuple,
    TokensDepositedEvent.OutputObject
  >;
  getEvent(
    key: "VaultCreated"
  ): TypedContractEvent<
    VaultCreatedEvent.InputTuple,
    VaultCreatedEvent.OutputTuple,
    VaultCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultUsed"
  ): TypedContractEvent<
    VaultUsedEvent.InputTuple,
    VaultUsedEvent.OutputTuple,
    VaultUsedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProviderApproved(address,string,uint8)": TypedContractEvent<
      ProviderApprovedEvent.InputTuple,
      ProviderApprovedEvent.OutputTuple,
      ProviderApprovedEvent.OutputObject
    >;
    ProviderApproved: TypedContractEvent<
      ProviderApprovedEvent.InputTuple,
      ProviderApprovedEvent.OutputTuple,
      ProviderApprovedEvent.OutputObject
    >;

    "TokensDeposited(address,uint256,uint256)": TypedContractEvent<
      TokensDepositedEvent.InputTuple,
      TokensDepositedEvent.OutputTuple,
      TokensDepositedEvent.OutputObject
    >;
    TokensDeposited: TypedContractEvent<
      TokensDepositedEvent.InputTuple,
      TokensDepositedEvent.OutputTuple,
      TokensDepositedEvent.OutputObject
    >;

    "VaultCreated(address,uint256,uint8,uint256)": TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;
    VaultCreated: TypedContractEvent<
      VaultCreatedEvent.InputTuple,
      VaultCreatedEvent.OutputTuple,
      VaultCreatedEvent.OutputObject
    >;

    "VaultUsed(address,uint256,address,uint256)": TypedContractEvent<
      VaultUsedEvent.InputTuple,
      VaultUsedEvent.OutputTuple,
      VaultUsedEvent.OutputObject
    >;
    VaultUsed: TypedContractEvent<
      VaultUsedEvent.InputTuple,
      VaultUsedEvent.OutputTuple,
      VaultUsedEvent.OutputObject
    >;
  };
}
