/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISoulboundToken__factory } from "./ISoulboundToken__factory";
export { RewardVault__factory } from "./RewardVault__factory";
