/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISoulboundToken,
  ISoulboundTokenInterface,
} from "../../../contracts/rewardvault.sol/ISoulboundToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "addressToTokenId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "hasMinted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "spendReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "tokenData",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "porBalance",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "totalEarned",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "currentTier",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "consecutiveMonths",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "lastRewardTime",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isActive",
            type: "bool",
          },
        ],
        internalType: "struct ISoulboundToken.TokenData",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ISoulboundToken__factory {
  static readonly abi = _abi;
  static createInterface(): ISoulboundTokenInterface {
    return new Interface(_abi) as ISoulboundTokenInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISoulboundToken {
    return new Contract(address, _abi, runner) as unknown as ISoulboundToken;
  }
}
